//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rtss_srv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rtss_srv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Chart.js v3.7.0
        /// * https://www.chartjs.org
        /// * (c) 2021 Chart.js Contributors
        /// * Released under the MIT License
        /// */
        ///!function(t,e){&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module?module.exports=e():&quot;function&quot;==typeof define&amp;&amp;define.amd?define(e):(t=&quot;undefined&quot;!=typeof globalThis?globalThis:t||self).Chart=e()}(this,(function(){&quot;use strict&quot;;const t=&quot;undefined&quot;==typeof window?function(t){return t()}:window.requestAnimationFrame;function e(e,i,s){const n=s||(t=&gt;Array.prototype.slice.call(t));let o=!1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string chart_min {
            get {
                return ResourceManager.GetString("chart_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/html&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Web console for RTSS&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;script rel=&quot;prefetch&quot; src=&quot;/static/chart.min.js&quot;&gt;&lt;/script&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/static/style.css&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        function getProcessList() {
        ///            return fetch(&apos;/pList&apos;)
        ///                .then((response) =&gt; response.json())
        ///                .then((responseJson [rest of string was truncated]&quot;;.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .inputLine {
        ///    margin-top: 12px;
        ///}
        ///.
        /// </summary>
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
